# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7051089b5d4d2c26b9f2a09a9c09a93d223d8177217f1329fe2033a612e03a084c79f77cd2fbdd8dd53685ebe045300bb18ac3c81ab120d8887077dd7947f635

test:
  secret_key_base: 44509edf6efd83f706a586120afa24c82abd0163f2cb13dec32c6a9b317a4db742c62b795fbfcabf13552fb1781a29caf16bb9c4e27d16eea9dd14c9354460b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
